[package]
name = "lit"
version = "0.1.0"
authors = ["maffei2443 <leoitu22hotmail.com@gmail.com>"]

[dependencies]
num-complex = "0.2"
image="*"
rand = "0.5.2"
rayon = "1.0.1"
[profile.dev]
opt-level=3
